# Generated by Django 3.1.2 on 2020-10-29 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201029_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_addon',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
