# Generated by Django 3.1.2 on 2020-10-30 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_addon',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
