# Generated by Django 3.1.2 on 2020-10-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201030_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('contact_subject', models.CharField(max_length=100)),
                ('contact_message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='shop/images'),
        ),
    ]
