# Generated by Django 3.1.2 on 2020-10-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201031_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='shop/images'),
        ),
    ]
