# Generated by Django 3.1.2 on 2020-10-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201031_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quatity',
            field=models.IntegerField(default=1),
        ),
    ]
