# Generated by Django 3.1.2 on 2020-10-31 19:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderDetail',
        ),
    ]
