# Generated by Django 3.1.2 on 2020-10-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201101_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
