# Generated by Django 3.1.2 on 2020-11-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201101_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='payment_id',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
