# Generated by Django 3.1.2 on 2020-11-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201101_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
