# Generated by Django 3.1.2 on 2020-10-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
                ('business_mobile', models.IntegerField()),
                ('business_email', models.CharField(max_length=50)),
                ('business_image', models.ImageField(default='', upload_to='business')),
            ],
        ),
    ]
