# Generated by Django 3.1.2 on 2020-10-28 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_image',
        ),
        migrations.AddField(
            model_name='business',
            name='credential',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='delivery_avail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='seller_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='servicable_area',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='service_discription',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
